export const routes = {
  home: "/",
  about: "/about",
  affiche: "/affiche",
  collectives: "/collectives",
  collective: "/collective",
  spaces: "/spaces",
  contacts: "/contacts",
  news: "/news",
  history: "/about/history",
  center: "/about/center",
  projects: "/about/projects",
  gallery: "/about/gallery",
  more: "/more",
  faq: "/faq",
};
